server:
  name: AstraSMP
  currency-name: Coins
  tax-rate: 0.08
  auction-limit-per-player: 12
  sell-cooldown-seconds: 2
  autosave-seconds: 120
  event-radius: 128
  world-name: world

storage:
  mode: yaml
  mysql:
    enabled: false
    host: localhost
    port: 3306
    database: astrasmp
    username: root
    password: password
    pool-size: 8

discord:
  enabled: true
  token: ""
  guild-id: ""
  chat-channel-id: ""
  log-channel-id: ""
  control-channel-id: ""
  linked-role-id: ""
  admin-role-id: ""
  prefix: "!as"

economy:
  prices:
    COBBLESTONE: 
    COAL: 
    RAW_IRON: 
    IRON_INGOT:
    RAW_GOLD: 
    GOLD_INGOT: 
    DIAMOND: 
    EMERALD: 
    NETHERITE_SCRAP: 
    REDSTONE: 
    LAPIS_LAZULI: 
    QUARTZ: 
    GLOWSTONE_DUST: 
    AMETHYST_SHARD: 
    ANCIENT_DEBRIS: 

events:
  meteor:
    interval-minutes: 180
    duration-minutes: 20
  airdrop:
    interval-minutes: 75
    duration-minutes: 10
  boss:
    interval-minutes: 120
    duration-minutes: 15
  chaos:
    interval-minutes: 300
    duration-minutes: 25
  treasure:
    interval-minutes: 110
    duration-minutes: 12

mmr:
  start: 1000
  bronze: 0
  silver: 1100
  gold: 1300
  diamond: 1600
  elite: 2000

contracts:
  bounty-fee: 0.10
  cancel-fee: 0.15
  max-active-per-player: 5

gui:
  title-color: "&8"
  filler: GRAY_STAINED_GLASS_PANE

spawn:
  world: "world"
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

locations:
  spawn: "world;26;68;444"
  pvp: "world;26;68;422"
  afk: "world;61;68;435"
  casino: "world;59.00;68.06;464.48"
  eventshop: "world;32.69;68.00;509.75"
  duel_pos1: "world;35;76;385"
  duel_pos2: "world;17;76;385"